name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

# This permission is required to create a release and upload assets.
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Using a slightly more common LTS version, adjust if you need 1.24 features

      # --- OS-SPECIFIC DEPENDENCIES ---
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: brew install libpcap

      - name: Download and extract Npcap SDK on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://nmap.org/npcap/dist/npcap-sdk-1.13.zip" -OutFile "npcap-sdk.zip"
          Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "npcap-sdk"

      - name: Extract tag name
        id: extract_tag
        # This works on all shells (bash, sh, pwsh) provided by GitHub Actions runners
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # --- BUILD STEPS (FIXED) ---
      # We use separate steps for Unix (Linux/macOS) and Windows to avoid shell syntax conflicts.

      - name: Build binary (Unix)
        if: runner.os != 'Windows'
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          mkdir -p dist
          OUT="gotraceroute-${TAG_NAME}-${GOOS}-${GOARCH}"
          go build -ldflags="-s -w" -o "dist/$OUT" ./cmd/gotraceroute.go

      - name: Build binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
          # Set absolute Windows SDK paths for CGO
          CGO_CFLAGS: "-I${{ github.workspace }}\\npcap-sdk\\Include"
          CGO_LDFLAGS: "-L${{ github.workspace }}\\npcap-sdk\\Lib\\${{ matrix.goarch }} -lwpcap"
        run: |
          New-Item -ItemType Directory -Path "dist" -Force
          $out = "gotraceroute-${env:TAG_NAME}-${env:GOOS}-${env:GOARCH}.exe"
          go build -ldflags="-s -w" -o "dist\$out" ./cmd/gotraceroute.go
      
      # --- CHECKSUM STEPS (IMPROVED) ---
      # Using native tools for each OS is more reliable.

      - name: Generate checksum (Unix)
        if: runner.os != 'Windows'
        run: |
          cd dist
          # Use shasum which is common on macOS and often available on Linux
          shasum -a 256 * > checksums.txt

      - name: Generate checksum (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd dist
          Get-FileHash * -Algorithm SHA256 | Format-Table -HideTableHeaders | Out-File -FilePath checksums.txt
          # The above command creates a file format like:
          # HASH                                PATH
          # 1234...  C:\actions-runner\_work\my-repo\my-repo\dist\gotraceroute-v1.0.0-windows-amd64.exe
          # We can clean it up to just be "hash  filename" for consistency
          (Get-Content checksums.txt) | ForEach-Object { $_.Trim() -replace '\s+', '  ' } | Set-Content checksums.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.goos }}-${{ matrix.goarch }}
          # The path now includes the checksum file
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # This will download all artifacts into a directory named 'dist'
          # with subdirectories for each artifact, e.g., dist/build-linux-amd64/
          path: dist

      - name: List downloaded files (for debugging)
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Prebuilt binaries and checksums for Linux, macOS, and Windows.
          # The glob pattern correctly finds all files in all subdirectories
          files: dist/**/*